---
booktitle: Proceedings of The 4th Workshop on Machine Learning for Interactive Systems
  at ICML 2015
volume: 43
year: '2015'
shortname: MLIS
published: 2015-06-18
start: 2015-07-11
end: 2015-07-11
sections:
- name: front
  title: Frontmatter
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: MLIS-2015
month: 0
cycles: false
editor:
- given: Heriberto
  family: Cuayáhuitl
- given: Nina
  family: Dethlefs
- given: Lutz
  family: Frommberger
- given: Martijn
  family: Van Otterlo
- given: Olivier
  family: Pietquin
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 4th Workshop on Machine Learning for Interactive Systems at ICML 2015
    Held in Lille, France on 11 July 2015

  Published as Volume 43 by the Proceedings of Machine Learning Research on 18 June 2015.

  Volume Edited by:
    Heriberto Cuayáhuitl
    Nina Dethlefs
    Lutz Frommberger
    Martijn Van Otterlo
    Olivier Pietquin

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 11 Jul
url: http://proceedings.mlr.press
baseurl: "/v43"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v43
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Machine Learning for Interactive Systems
  url: 
  location: Lille, France
  dates:
  - 2015-07-11
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v43.bib
---
